RNN 기반의 LM과 Transformer 계열의 LM의 가장 큰 차이점은?			

	아키텍처 구조			
		순환 신경망 vs 인코더 디코더 구조(+셀프어텐선 피드포워드 레이어 등으로 구성)		
				
	학습속도와 병렬처리			
		attention vs self attention		
		순환 처리 vs 병렬 처리		
	장기 의존성 모델링			
		긴 시퀀스 처리 정도		
	메모리 요구량			
		과거 정보 vs self attention 		
	결국 self attention이 가장 큰 차이로 보임			
				
		이전단어 + 시퀀스 내 주어진 단어		
		시퀀스 내 주어진 모든 단어		
				
				
	self attention이란?			
				
	attention과 self attention의 차이			

### attention

In [40]:
import numpy as np

def attention(query, keys, values):
    # 쿼리와 키의 내적
    scores = np.dot(query, keys.T)

    
    # 소프트맥스 함수를 사용하여 어텐션 가중치 계산
    attention_weights = softmax(scores)
    
    # 가중 평균 계산
    outputs = np.dot(attention_weights, values)
    
    return outputs, attention_weights #아웃풋과 가중 평균 리턴

def softmax(x):
    ex_x = np.exp(x)
    result = ex_x/np.sum(ex_x, axis=-1, keepdims=True)
    #소프트 맥스 함수 구현
 
    return result

# 입력 시퀀스 및 쿼리 생성
inputs = np.random.rand(3, 4)
# numpy array 3*3 생성 랜덤 생성 0~1값
query = np.random.rand(1, 4)
# numpy array 1*3 생성 랜덤 생성 0~1값

# 키와 값은 입력과 동일하게 설정
keys = inputs
values = inputs

# Attention 함수 호출
attention_output, attention_weights = attention(query, keys, values)

print("Attention 출력:", attention_output)
print("Attention 가중치:", attention_weights)

Attention 출력: [[0.41954816 0.37053324 0.50633831 0.37451849]]
Attention 가중치: [[0.4257442  0.35472567 0.21953012]]


### self-attention

In [37]:
import numpy as np

def self_attention(inputs):
    # 입력 행렬의 크기
    seq_len, embed_dim = inputs.shape
    
    # 쿼리, 키, 값 행렬 생성
    queries = inputs
    keys = inputs
    values = inputs
    
    # 쿼리와 키의 내적
    scores = np.dot(queries, keys.T)

    
    # 소프트맥스 함수를 사용하여 어텐션 가중치 계산
    attention_weights = softmax(scores)

    # 가중 평균 계산
    outputs = np.dot(attention_weights, scores)
    
    return outputs, attention_weights

def softmax(x):
    #소프트 맥스 함수 구현
    exp_x = np.exp(x)
    result = exp_x/np.sum(exp_x, axis=-1, keepdims=True)
    return result

# 입력 시퀀스 생성
inputs = np.random.rand(3,3)# numpy array 3*3 생성 랜덤 생성 0~1값

# Self-Attention 함수 호출
self_attention_output, self_attention_weights = self_attention(inputs)

print("Self-Attention 출력:", self_attention_output)
print("Self-Attention 가중치:", self_attention_weights)

Self-Attention 출력: [[1.05025364 1.00416134 0.63800809]
 [1.05120222 1.00857821 0.63790585]
 [1.03347266 0.98628393 0.62897492]]
Self-Attention 가중치: [[0.39499636 0.35837366 0.24662998]
 [0.37463132 0.38657976 0.23878892]
 [0.37104345 0.34365691 0.28529964]]
